// flow-typed signature: 76763177db5346744bb9a911d7f4a117
// flow-typed version: <<STUB>>/spotify-web-api-node_v^2.3.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spotify-web-api-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spotify-web-api-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spotify-web-api-node/examples/access-token-refresh' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/access-token-using-client-credentials' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/add-remove-replace-tracks-in-a-playlist' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/add-tracks-to-a-playlist' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/get-info-about-current-user' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/get-related-artists' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/get-top-tracks-for-artist' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/examples/search-for-tracks' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/authentication-request' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/base-request' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/client' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/http-manager' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/server-methods' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/server' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/spotify-web-api' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/webapi-error' {
  declare module.exports: any;
}

declare module 'spotify-web-api-node/src/webapi-request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spotify-web-api-node/examples/access-token-refresh.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/access-token-refresh'>;
}
declare module 'spotify-web-api-node/examples/access-token-using-client-credentials.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/access-token-using-client-credentials'>;
}
declare module 'spotify-web-api-node/examples/add-remove-replace-tracks-in-a-playlist.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/add-remove-replace-tracks-in-a-playlist'>;
}
declare module 'spotify-web-api-node/examples/add-tracks-to-a-playlist.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/add-tracks-to-a-playlist'>;
}
declare module 'spotify-web-api-node/examples/get-info-about-current-user.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/get-info-about-current-user'>;
}
declare module 'spotify-web-api-node/examples/get-related-artists.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/get-related-artists'>;
}
declare module 'spotify-web-api-node/examples/get-top-tracks-for-artist.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/get-top-tracks-for-artist'>;
}
declare module 'spotify-web-api-node/examples/search-for-tracks.js' {
  declare module.exports: $Exports<'spotify-web-api-node/examples/search-for-tracks'>;
}
declare module 'spotify-web-api-node/src/authentication-request.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/authentication-request'>;
}
declare module 'spotify-web-api-node/src/base-request.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/base-request'>;
}
declare module 'spotify-web-api-node/src/client.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/client'>;
}
declare module 'spotify-web-api-node/src/http-manager.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/http-manager'>;
}
declare module 'spotify-web-api-node/src/server-methods.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/server-methods'>;
}
declare module 'spotify-web-api-node/src/server.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/server'>;
}
declare module 'spotify-web-api-node/src/spotify-web-api.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/spotify-web-api'>;
}
declare module 'spotify-web-api-node/src/webapi-error.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/webapi-error'>;
}
declare module 'spotify-web-api-node/src/webapi-request.js' {
  declare module.exports: $Exports<'spotify-web-api-node/src/webapi-request'>;
}
